### ISSUE TITLE
OpenSSL Library is not found

### ISSUE THREAD

**Issue by gigicu01** [ajoliat23/blockBook#1]
Whenever we try to install or use anchor, it says that the OpenSSL library is not found. Installing OpenSSL manually worked to get Anchor installed after, but using Anchor Test on the first project doesn't work. I get OpenSSL is missing error which I can't get rid of even if I create the symbolic link (since there is really no file with the name it looks for, but OpenSSL is installed with version 3.0.2 on my Ubuntu vm). Here is the error I get: "/home/gpantelimon23/.rustup/toolchains/bpf/bin/cargo: /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by /home/gpantelimon23/.rustup/toolchains/bpf/bin/cargo)"

Thinking about finding a way to install OpenSSL 1.1 which might solve the problem

**Comment by Zachtmac1** [comment]
Use Ubuntu dual boot nerd

**Comment by gigicu01** [comment]
This issue was solved by installing Ubuntu alongside Windows and also making sure the version is 20.04 which seems to have less issues than 22.04. Anchor test was successfully run on a dummy project and the validator seems to be working well. The VS Code was also set up properly on Ubuntu and was tested with identical results.
