### ISSUE TITLE
Inconsistent Package Access

### ISSUE THREAD

**Issue by E0MCH1NA** [ajoliat23/blockBook#10]
With Ubuntu 22.04 after installing rust and solana and closing the window after each there were instances where the terminal would claim that there was no installation of these said packages. For rust these commands were [rustup --version, rustc --version, cargo --version], and in the case of Solana, the solana --version was inconsistent. In order to have these commands work I was required to restart my computer entirely and then close and open the Ubuntu 22.04 terminal window until both commands would output as successful.  After attempting to also install an older version of OpenSSL after downgrading from 3.0.2 I was also getting this issue and was unable to resolve it. 

The fix that I have found for these issues is simply using Ubuntu 20.04 instead of the 22.04 release, as since the move I have had no issues.

**Comment by jgurary** [comment]
Seems closed!
