### ISSUE TITLE
Anchor Test Command Test-Validator Startup Issue

### ISSUE THREAD

**Issue by E0MCH1NA** [ajoliat23/blockBook#11]
When trying to run Anchor test command within my project folder I am presented with this issue. 

![anchor_test](https://user-images.githubusercontent.com/77904047/190768143-e5cf9571-ad95-4e59-bd07-06324b80b9fb.JPG)

After digging into the logs for this issue I found that the problem is stemming from this command trying to increase the maximum open file descriptor limit from 1024 to 1000000. After researching into this issue I have found that this must be handled in the etc/security/limits.conf file. Although I am having trouble configuring this new limit as the default values are unchangeable. 

Might be time to try Dual Booting...

**Comment by jgurary** [comment]
Almost certainly Windows being weird.
