### ISSUE TITLE
Account does not exist when trying to fetch

### ISSUE THREAD

**Issue by gigicu01** [ajoliat23/blockBook#14]
Currently trying to figure out why I get the error in the title when trying to fetch. I believe it has to do with the fact the the transaction does not have enough time to process since I actually managed to fetch the account a few times. I tried to use await but it still seems to not be working. Will have to look more into it.

![image](https://user-images.githubusercontent.com/80425896/192044977-6388b42d-3fc8-4a38-9e88-8cde30f8d7ab.png)

**Comment by gigicu01** [comment]
Update: logged the transaction result in the console and got an actual results, but I think the transaction is not actually creating the account which is why it can't find the account when trying to fetch. I tried to get the account info using solana and log it too and got a null result as shown below:

![image](https://user-images.githubusercontent.com/80425896/192047213-d168c847-cc8b-4848-9c71-7dbcdb422e83.png)

**Comment by jgurary** [comment]
Should be solved with the recent update I sent you, the tx to create the account was not actually being sent.

**Comment by gigicu01** [comment]
Issue solved. The problem was as stated above by @jgurary.

**Comment by gigicu01** [comment]
Issue solved. The problem was as stated above by @jgurary.
