### ISSUE TITLE
connect wallet added, but can't be clicked

### ISSUE THREAD

**Issue by ajoliat23** [ajoliat23/blockBook#16]
So I followed a new tutorial to connect the wallet since the other ones weren't working very well.
https://www.0xdev.co/how-to-connect-to-a-solana-wallet-to-your-react-app/
Everything runs and you can see the button, however, when you click it nothing happens. I can't seem to figure out why it won't work and I've been looking for hours. If anyone else wants to take a look I'm going to put the code on a new branch.

**Comment by jgurary** [comment]
Check out how some protocol like Ray does it: https://github.com/raydium-io/raydium-frontend
