### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by MSGSmith** [ajoliat23/blockBook#6]
The react code is sending back an error claiming that the start script does not exist, but in the package.json, there clearly is a start method. Any thoughts?

**Comment by Zachtmac1** [comment]
Yeah the start command is in there, but it references the react-script start, which references index.html, which seems not to be on main right now. Once Lexi adds it to main, that part of the issue should be solved

**Comment by ajoliat23** [comment]
Just added it, sorry guys
