### ISSUE TITLE
Wallet Adapter Issue

### ISSUE THREAD

**Issue by Zachtmac1** [ajoliat23/blockBook#7]
I followed the github starter for the wallet adapter, went through and updated the dependency list, added a couple new files and did a lot of debugging for it. However, the code is still not at a spot where it is ready to be committed to main. NPM start does kick open localhost 3000, but it does not receive any data from the files to show the UI. Lexi I saw you were able to see the UI by using NPM start earlier this week...any tips? Other than that, if anyone wants to work on the code they are welcome to, and I will plan on digging further into this adapter at the start of next week.

**Comment by Zachtmac1** [comment]
![image](https://user-images.githubusercontent.com/81589146/190714310-57549e43-1055-4ccd-a806-5170c9385879.png)

**Comment by Zachtmac1** [comment]
![image](https://user-images.githubusercontent.com/81589146/190714408-fe3fd7d4-f9ce-4168-8bf7-31e1e32c0c9d.png)

**Comment by ajoliat23** [comment]
it might be an issue with the build/node modules that weren't committed to git with the rest of the react application, i'll take a look at it tonight to see if i can figure it out

**Comment by ajoliat23** [comment]
i just added manifest.json and a build folder with some stuff in it to the aj-react-correct branch so all of the original react files that i first uploaded that weren't running do run in that branch once it is in the react folder (i tested it) i am going to add the wallet adapt files and see if it breaks anything

**Comment by Zachtmac1** [comment]
Respond below with the results and if they work we can create a pull request for main and then I’ll close this issue.
