### ISSUE TITLE
Solana Install Timeout

### ISSUE THREAD

**Issue by E0MCH1NA** [ajoliat23/blockBook#8]
When trying to run the sh -c "$(curl -sSfL https://release.solana.com/v1.9.4/install)" command in Ubuntu 20.04 a problem arose in regards to running into a timeout when downloading the installation package. In order to resolve this a timeout parameter needed to be adjusted to twice as long as the default setting. After this was done the specific version of 1.9.4 still was unable to finish, yet in the case of version 1.10.4, there were no issues.

**Comment by jgurary** [comment]
Seems closed!
