### ISSUE TITLE
OpenSSL Issue for Anchor Install

### ISSUE THREAD

**Issue by E0MCH1NA** [ajoliat23/blockBook#9]
When trying to run "cargo install --git https://github.com/project-serum/anchor anchor-cli --locked" command in order to install Anchor I was getting an error stating that "/home/gloves/.rustup/toolchains/bpf/bin/cargo: /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by /home/gloves/.rustup/toolchains/bpf/bin/cargo)" . Originally I ran into this problem when using Ubuntu 22.04 which comes with OpenSSL 3.0.2, therefore I proceeded to remove that version and reinstall OpenSSL with the required version of "1.1.x", yet this was fruitless. After deliberation and research I migrated to Ubuntu 20.04 which comes pre-baked with this required version and at this point in the process the cargo install command began to work properly.

**Comment by jgurary** [comment]
Seems closed!
